apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:3
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kuard.j9z.cz.
    external-dns.alpha.kubernetes.io/ttl: "60"
    #service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Product=Risk,CostCenter=665050,Creator=en341
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: kuard
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  labels:
    app: kuard
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kuard-ing.j9z.cz.
    external-dns.alpha.kubernetes.io/ttl: "60"
  #  kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: kuard-ing.j9z.cz
    http:
      paths:
      - backend:
          serviceName: kuard
          servicePort: 80
